version: '1'

services:
  php:
    image: php:8.3-apache
    container_name: php83
    ports:
      - 8000:80
    volumes:
      - ./php:/var/www/html
    build:
      context: .
      dockerfile: DockerFile
  mysql:
    image: mysql:8.4.3
    container_name: mysql843
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8081:80

volumes:
  dbdata: